DELETE_OUTLINE_COLOR = "#ee82ee"
MERGE_OUTLINE_COLOR = "#54ff9f"
ADD_OUTLINE_COLOR = "#7b68ee"

BOX_COLOR = "#87cefa"
GRID_COLOR = "#44a1c9"

RADIO_SELECT_COLOR = "#4b0082"
PROGRESS_COLOR = "#8a2be2"

SLICE_TYPES = ["Row x Column", "Fixed Size", "Auto Detection"]
